version: '3.8'
services:
  nginx-pm:
    container_name: nginx-pm
    hostname: nginx-pm
    image: jc21/nginx-proxy-manager:latest
    volumes:
      - /env/appdata/nginx-pm:/data
      - /env/appdata/nginx-pm/letsencrypt:/etc/letsencrypt
    ports:
      - 50080:80
      - 81:81
      - 50443:443
    restart: unless-stopped