version: '3.8'
services:
  nginx-pm:
    container_name: nginx-pm
    image: jc21/nginx-proxy-manager:latest
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    ports:
      - 50080:80
      - 81:81
      - 50443:443
    restart: unless-stopped