version: "3.3"

services:

  homepage:
    container_name: homepage
    hostname: dreamcast.homepage
    image: ghcr.io/gethomepage/homepage:latest
    volumes:
      - /env/appdata/homepage:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /env/appdata/homepage/images:/app/public/images
    ports:
      - 85:3000
    restart: always